export const DIMENSIONS = ["compensation", "growth", "lifestyle", "stability", "mission"];

export const WEIGHT_PRESETS = {
  "Compensation First": { compensation: 35, growth: 20, lifestyle: 15, stability: 15, mission: 15 },
  "Growth First": { compensation: 20, growth: 35, lifestyle: 15, stability: 10, mission: 20 },
  "Balance First": { compensation: 20, growth: 20, lifestyle: 25, stability: 20, mission: 15 },
  "Low Risk": { compensation: 15, growth: 15, lifestyle: 20, stability: 35, mission: 15 },
};

export const FIELD_LABELS = {
  baseSalary: "Base salary",
  targetBonus: "Target bonus",
  annualizedEquityEstimate: "Annualized equity estimate",
  ptoDays: "PTO days",
  remoteFlexibility: "Remote flexibility",
  onsiteDays: "Onsite days/week",
  scope: "Scope",
  mentorship: "Mentorship",
  brandSignal: "Brand signal",
  stability: "Stability",
  missionFit: "Mission fit",
  workloadIntensity: "Workload intensity",
  nearTermEarnings: "Near-term earnings",
  upsidePotential: "Upside potential",
  skillCompounding: "Skill compounding",
  optionality: "Optionality",
  autonomy: "Autonomy",
  lifestyleSustainability: "Lifestyle sustainability",
  networkBrand: "Network/brand",
  downsideRisk: "Downside risk",
};

export const FIELD_HINTS = {
  baseSalary: "CAD or USD equivalent. Fictional demo values.",
  targetBonus: "Expected annual target, not guaranteed.",
  annualizedEquityEstimate: "Estimated annual value before liquidity or valuation checks.",
  ptoDays: "Annual paid time off.",
  remoteFlexibility: "1 means low flexibility. 10 means high flexibility.",
  onsiteDays: "Expected days onsite each week.",
  scope: "Role scope and ownership.",
  mentorship: "Expected manager and peer learning support.",
  brandSignal: "Resume and network signal from the organization.",
  stability: "Perceived organizational or path stability.",
  missionFit: "How strongly the work fits the user's priorities.",
  workloadIntensity: "1 means low intensity. 10 means high intensity.",
  nearTermEarnings: "Expected earning power in the next 12-24 months.",
  upsidePotential: "Longer-term economic upside.",
  skillCompounding: "How much the path builds reusable capability.",
  optionality: "How many future paths it opens.",
  autonomy: "Control over work, pace, and direction.",
  lifestyleSustainability: "Whether the path looks sustainable over time.",
  networkBrand: "Access to people, credibility, and future opportunities.",
  downsideRisk: "1 means low downside risk. 10 means high downside risk.",
};

export const DEMO_SCENARIOS = [
  {
    id: "offers-core",
    label: "Offer A vs Offer B vs Stay Put",
    mode: "job-offers",
    options: [
      {
        id: "offer-a",
        title: "Offer A",
        subtitle: "Senior product role at an established software company",
        mode: "job-offers",
        inputs: {
          baseSalary: 128000,
          targetBonus: 12000,
          annualizedEquityEstimate: 18000,
          ptoDays: 20,
          remoteFlexibility: 8,
          onsiteDays: 2,
          scope: 7,
          mentorship: 8,
          brandSignal: 7,
          stability: 8,
          missionFit: 6,
          workloadIntensity: 6,
        },
      },
      {
        id: "offer-b",
        title: "Offer B",
        subtitle: "High-upside operator role at a venture-backed startup",
        mode: "job-offers",
        inputs: {
          baseSalary: 112000,
          targetBonus: 5000,
          annualizedEquityEstimate: 62000,
          ptoDays: 15,
          remoteFlexibility: 6,
          onsiteDays: 3,
          scope: 9,
          mentorship: 5,
          brandSignal: 6,
          stability: 4,
          missionFit: 8,
          workloadIntensity: 9,
        },
      },
      {
        id: "stay-put",
        title: "Stay Put",
        subtitle: "Current role with known team and lower transition risk",
        mode: "job-offers",
        inputs: {
          baseSalary: 118000,
          targetBonus: 8000,
          annualizedEquityEstimate: 9000,
          ptoDays: 22,
          remoteFlexibility: 9,
          onsiteDays: 1,
          scope: 5,
          mentorship: 6,
          brandSignal: 5,
          stability: 9,
          missionFit: 5,
          workloadIntensity: 5,
        },
      },
    ],
  },
  {
    id: "paths-core",
    label: "Established Company vs Startup vs Independent",
    mode: "career-paths",
    options: [
      {
        id: "established",
        title: "Established Company",
        subtitle: "Build depth inside a mature product organization",
        mode: "career-paths",
        inputs: {
          nearTermEarnings: 8,
          upsidePotential: 6,
          skillCompounding: 7,
          optionality: 7,
          autonomy: 5,
          lifestyleSustainability: 8,
          stability: 9,
          networkBrand: 8,
          missionFit: 6,
          downsideRisk: 3,
        },
      },
      {
        id: "startup",
        title: "Startup Path",
        subtitle: "Take on broader scope with higher variance",
        mode: "career-paths",
        inputs: {
          nearTermEarnings: 6,
          upsidePotential: 9,
          skillCompounding: 9,
          optionality: 8,
          autonomy: 7,
          lifestyleSustainability: 4,
          stability: 4,
          networkBrand: 7,
          missionFit: 8,
          downsideRisk: 8,
        },
      },
      {
        id: "independent",
        title: "Independent",
        subtitle: "Consulting and productized services while building a client base",
        mode: "career-paths",
        inputs: {
          nearTermEarnings: 5,
          upsidePotential: 8,
          skillCompounding: 8,
          optionality: 9,
          autonomy: 10,
          lifestyleSustainability: 5,
          stability: 3,
          networkBrand: 6,
          missionFit: 9,
          downsideRisk: 7,
        },
      },
    ],
  },
  {
    id: "product-roles",
    label: "Three Product Roles",
    mode: "job-offers",
    options: [
      {
        id: "platform-pm",
        title: "Platform PM",
        subtitle: "Infrastructure-facing role with deep technical peers",
        mode: "job-offers",
        inputs: {
          baseSalary: 132000,
          targetBonus: 10000,
          annualizedEquityEstimate: 22000,
          ptoDays: 18,
          remoteFlexibility: 7,
          onsiteDays: 2,
          scope: 8,
          mentorship: 7,
          brandSignal: 8,
          stability: 7,
          missionFit: 6,
          workloadIntensity: 7,
        },
      },
      {
        id: "growth-pm",
        title: "Growth PM",
        subtitle: "Experimentation-heavy role with visible business metrics",
        mode: "job-offers",
        inputs: {
          baseSalary: 126000,
          targetBonus: 18000,
          annualizedEquityEstimate: 14000,
          ptoDays: 17,
          remoteFlexibility: 6,
          onsiteDays: 3,
          scope: 8,
          mentorship: 6,
          brandSignal: 7,
          stability: 7,
          missionFit: 5,
          workloadIntensity: 8,
        },
      },
      {
        id: "ai-tools-pm",
        title: "AI Tools PM",
        subtitle: "Ambiguous zero-to-one role in an emerging product area",
        mode: "job-offers",
        inputs: {
          baseSalary: 120000,
          targetBonus: 6000,
          annualizedEquityEstimate: 36000,
          ptoDays: 16,
          remoteFlexibility: 8,
          onsiteDays: 1,
          scope: 9,
          mentorship: 5,
          brandSignal: 6,
          stability: 5,
          missionFit: 9,
          workloadIntensity: 8,
        },
      },
    ],
  },
];
